POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Aarav Sharma",
  "email": "aarav.sharma26@example.com",
  "address": "Lucknow, Uttar Pradesh",
  "birthDate": "2003-08-15",
  "registeredDate": "2026-09-26"
}