spring.application.name=billing-service

server.port=4001
grpc.server.port=9001

#spring.datasource.url=jdbc:postgresql://localhost:5002/db
#spring.datasource.username=admin_user
#spring.datasource.password=password

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always

# Kafka Consumer — override SPRING_KAFKA_BOOTSTRAP_SERVERS in Docker
spring.kafka.bootstrap-servers=kafka:9092 
#container name is kafka
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer